---
kind: ShellScript
version: v1
metadata:
  name: common-shellscript
  skipDeleteAll: true
  environments:
  - sandbox1
  - sandbox2
spec:
  source:
    type: inline
    value: !Sub
    - 'echo "COMMON SHELLSCRIPT EXECUTED - Action: ${action} with logging level set to ${debugLevel}"'
    - action: !Variable std::action
      debugLevel: !Value demo-project-log-level
  convertOutputToText: true
  stripNewline: True
  convertRepeatingSpaces: true
  stripLeadingTrailingSpaces: true
---
kind: TestExtension
version: v1
metadata:
  name: test1
  skipDeleteAll: true
  environments:
  - sandbox1
  - sandbox2
spec:
  test: true